stages:
  - build
  - test

variables:
  IMAGE_NAME: my-image-name
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_REGISTRY: my-docker-registry

before_script:
  - apt-get update && apt-get install -y docker.io
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $DOCKER_REGISTRY

build:
  stage: build
  image: ubuntu:latest
  script:
    - export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
    - source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/atlasLocalSetup.sh
    - asetup AnalysisBase,22.2.60
    - mkdir -p build
    - cmake -S Reweighter -B build
    - make -C build
    - source build/*/setup.sh
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

test:
  stage: test
  image: $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  script:
    - reweight --configFile config_1l.cfg

