
executable = /scratch4/levans/data-driven-reweighting/Condor/reweight.sh
arguments = $config $(ClusterId)$(ProcId)
universe = vanilla
+MaxRuntime = 3600

output = /scratch4/levans/data-driven-reweighting/Condor/output/output_$config_.$(ClusterId)$(ProcId).out
error = /scratch4/levans/data-driven-reweighting/Condor/error/error_$config_.$(ClusterId)$(ProcId).err
log = /scratch4/levans/data-driven-reweighting/Condor/log/log_$config_.$(ClusterId)$(ProcId).log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue 


